import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import Header from './components/Header'
import './globals.css'

const inter = Roboto({ subsets: ['latin'], weight: '100' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
